# Generated by Django 5.1.2 on 2025-05-13 03:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_description_document_summary_document_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_llm_models',
        ),
        migrations.AddField(
            model_name='document',
            name='summarization_model',
            field=models.CharField(default="", max_length=100),
        ),
        migrations.DeleteModel(
            name='LLMModel',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_llm_models',
            field=models.JSONField(blank=True, default=list, help_text='List of LLM model codes that this user has favorited', null=True),
        ),
    ]
