# Generated by Django 5.1.2 on 2025-05-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_user_favorite_llm_models_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_llm_models',
        ),
    ]
