# Generated by Django 5.1.2 on 2025-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_is_dev_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/media/default-avatar.jpg', max_length=255),
        ),
    ]
