# Generated by Django 5.1.2 on 2025-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_chat_model',
            field=models.CharField(default='llama3.1:8b', help_text='The default chat model to use for documents', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='default_markdown_converter',
            field=models.CharField(default='marker', help_text='The default converter to use for documents', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='default_summarization_model',
            field=models.CharField(default='llama3.1:8b', help_text='The default summarization model to use for documents', max_length=255),
        ),
    ]
