# Generated by Django 5.1.2 on 2026-10-07 03:07

from django.db import migrations, models

# Tags pull-llms.sh no longer pulls; users still pointing at them would hit
# "model not found", so they move to the new default.
RETIRED_MODELS = [
    "llama3.1:8b",
    "llama3.1:8b-text-fp16",
    "llama3.2:1b",
    "qwen2.5:7b-instruct-q4_K_M",
    "hermes3:3b",
    "qwen3:0.7b",
    "qwen3:4b",  # now the thinking-only release; far too slow on CPU
]
NEW_DEFAULT = "qwen3:4b-instruct-2507-q4_K_M"


def move_users_off_retired_models(apps, schema_editor):
    User = apps.get_model("app", "User")
    for field in ("default_chat_model", "default_summarization_model"):
        User.objects.filter(**{f"{field}__in": RETIRED_MODELS}).update(**{field: NEW_DEFAULT})


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_document_tags_document_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_chat_model',
            field=models.CharField(default='qwen3:4b-instruct-2507-q4_K_M', help_text='The default chat model to use for documents', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_summarization_model',
            field=models.CharField(default='qwen3:4b-instruct-2507-q4_K_M', help_text='The default summarization model to use for documents', max_length=255),
        ),
        migrations.RunPython(move_users_off_retired_models, migrations.RunPython.noop),
    ]
