# Generated by Django 5.1.2 on 2026-10-07 04:48

from django.db import migrations, models

# Roles were saved as str(UserRole.X), e.g. "UserRole.SUPER_ADMIN", instead of the
# enum value, so no user was ever recognised as an admin.
ROLE_VALUES = {"UserRole.USER": "user", "UserRole.ADMIN": "admin", "UserRole.SUPER_ADMIN": "super_admin"}


def store_role_values(apps, schema_editor):
    User = apps.get_model("app", "User")
    for stored, value in ROLE_VALUES.items():
        User.objects.filter(role=stored).update(role=value)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_qwen3_model_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN'), ('super_admin', 'SUPER_ADMIN')], default='user', max_length=20),
        ),
        migrations.RunPython(store_role_values, migrations.RunPython.noop),
    ]
