# Generated by Django 5.1.2 on 2026-10-07 05:28
"""CATSight v2: own chunk table (pgvector + full-text), simpler pipeline statuses,
guest/demo support. Old LangChain vector tables are dropped; documents are re-indexed."""

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


# Old nine-step statuses -> the five pipeline stages
STATUS_MAP = {
    "pending": "queued",
    "processing": "queued",
    "text_extracting": "extracting",
    "text_extraction_done": "summarizing",
    "generating_summary": "summarizing",
    "summary_generation_done": "indexing",
    "embedding_text": "indexing",
    "text_embedding_done": "indexing",
    "completed": "ready",
}


def map_statuses(apps, schema_editor):
    Document = apps.get_model("app", "Document")
    History = apps.get_model("app", "DocumentStatusHistory")
    for old, new in STATUS_MAP.items():
        # Chunks lived in the dropped LangChain tables, so finished documents must re-index
        Document.objects.filter(status=old).update(status="indexing" if new == "ready" else new)
        History.objects.filter(status=old).update(status=new)
    History.objects.filter(changed_at__isnull=True).delete()  # pre-created placeholders


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_role_values'),
    ]

    operations = [
        # First, while history rows can still be NULL-dated placeholders
        migrations.RunPython(map_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('context', models.CharField(blank=True, default='', max_length=500)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'ordering': ['document_id', 'index'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('upload', 'Upload'), ('message', 'Message')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='documentstatushistory',
            options={'ordering': ['changed_at', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='app_chat_updated_41c36a_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentstatushistory',
            name='app_documen_changed_a05fe9_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='app_tag_name_c400d7_idx',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='markdown_converter',
        ),
        migrations.RemoveField(
            model_name='document',
            name='no_of_chunks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_chat_model',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_markdown_converter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_summarization_model',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_dev_mode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_onboarded',
        ),
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='extractor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='progress_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentstatushistory',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='blurhash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='preview_image',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('summarizing', 'Summarizing'), ('indexing', 'Indexing'), ('ready', 'Ready')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='summarization_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentfulltext',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulltext', to='app.document'),
        ),
        migrations.AlterField(
            model_name='documentstatushistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentstatushistory',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'GUEST'), ('user', 'USER'), ('admin', 'ADMIN'), ('super_admin', 'SUPER_ADMIN')], default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-updated_at'], name='app_chat_user_id_45a9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['year'], name='app_documen_year_88b570_idx'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='app.document'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_gin'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'index'), name='unique_chunk_index'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'kind', 'created_at'], name='app_usageev_user_id_846d49_idx'),
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS langchain_pg_embedding; DROP TABLE IF EXISTS langchain_pg_collection;",
            migrations.RunSQL.noop,
        ),
    ]
