# Generated by Django 5.1.15 on 2026-10-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_curate_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
    ]
