# Generated by Django 5.1.15 on 2026-10-10 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_google_sign_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_provider', models.CharField(blank=True, choices=[('openrouter', 'Openrouter'), ('openai', 'Openai'), ('ollama', 'Ollama')], default='', max_length=20)),
                ('ai_api_key', models.TextField(blank=True, default='')),
                ('ai_api_key_last4', models.CharField(blank=True, default='', max_length=4)),
                ('chat_model', models.CharField(blank=True, default='', max_length=200)),
                ('fast_model', models.CharField(blank=True, default='', max_length=200)),
                ('ocr_model', models.CharField(blank=True, default='', max_length=200)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=200)),
                ('reranker_model', models.CharField(blank=True, default='', max_length=200)),
                ('ollama_allowed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='app_chat_user_id_45a9ce_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'GUEST'), ('user', 'USER'), ('super_admin', 'SUPER_ADMIN')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.organization'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.organization'),
        ),
        migrations.AddField(
            model_name='chat',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='app.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.organization'),
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.organization'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.organization'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'organization', '-updated_at'], name='app_chat_user_id_daf242_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'file_hash'], name='app_documen_organiz_f4a9fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_membership'),
        ),
    ]
